name: Update Version

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update version in secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ github.event.inputs.new_version }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/VERSION \
            -d '{"encrypted_value":"'"$NEW_VERSION"'"}'